version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
       - "8080:80"
    depends_on:
      - app
    container_name: laravel-nginx

  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - postgres
    container_name: laravel-app

  postgres:
    image: postgres:latest
    ports:
        - "15432:5432"
    restart: on-failure
    volumes:
        - /var/lib/postgresql/data/gggff
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/gggff
    container_name: laravel-postgres
